### ISSUE TITLE
Doesn't work anymore (The pages it downloads are empty)

### ISSUE THREAD

**Issue by gamesbe** [gzuri/HorribleSubs-Downloader#1]
It could be due to the fact that HS changed the design layout of the site.

My config file before it stopped working:

http://pastebin.com/wL16KgNt

**Comment by gamesbe** [comment]
Can you please compile the new build as well? Thanks.

**Comment by gzuri** [comment]
Thank you for reporting, they have indeed changed the site structure. Everything is fixed now, and the new compile version is online. 

Your feedback gave me the idea to implement fallback on video quality since I saw that not all anime is encoded in 1080.
